require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml
  - rubocop/layout.yml
  - rubocop/lint.yml
  - rubocop/metrics.yml
  - rubocop/performance.yml
  - rubocop/rspec.yml
  - rubocop/style.yml

AllCops:
  Exclude:
    - gemfiles/**/*
    - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 3.0

# Broken: https://github.com/rubocop/rubocop/issues/12113
Bundler/DuplicatedGroup:
  Enabled: false
