#!/usr/bin/env bash

set -Eeuxo pipefail

rm -f ./Gemfile.lock
bundle install

rm -f ./gemfiles/*.gemfile ./gemfiles/*.gemfile.lock
bundle exec appraisal generate

# XXX: `bundle exec appraisal install` fails on ruby-3.2
for BUNDLE_GEMFILE in gemfiles/*.gemfile; do
  export BUNDLE_GEMFILE
  bundle check || bundle install
done
